steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-image-name:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-image-name:$COMMIT_SHA']

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/your-image-name:$COMMIT_SHA'

# Specify where to store the build logs
options:
  logging: CLOUD_LOGGING_ONLY
